language: objective-c
osx_image: xcode8.3
env:
  - PLATFORM=iOS NAME='iPhone SE'
  - PLATFORM=tvOS NAME='Apple TV 1080p'
before_install:
  - export UUID=$(instruments -s | ruby -e "ARGF.each_line{ |ln| ln =~ /$NAME .* \[(.*)\]/; if \$1; puts(\$1); exit; end }");
install:
  - carthage bootstrap --platform $PLATFORM
script:
  - set -o pipefail;
    open -a "simulator" --args -CurrentDeviceUDID "$UUID";
    xcodebuild -scheme PMKUIKit -destination "id=$UUID" test | xcpretty
